brew "curl"
brew "docker"
brew "dockutil"
brew "fastfetch"
brew "fzf"
brew "gh"
brew "git"
brew "mas"
brew "node"
brew "openjdk"
brew "postgresql@15", restart_service: :changed
brew "pyenv"
brew "rbenv"
brew "scrcpy"
brew "android-platform-tools"
brew "wget"
brew "yarn"

cask "brave-browser"
cask "android-studio"
cask "coconutbattery"
cask "docker-desktop"
cask "font-meslo-for-powerlevel10k"
cask "github"
cask "localsend"
cask "localxpose"
cask "mac-mouse-fix"
cask "middleclick"
cask "notion"
cask "postman"
cask "proton-pass"
cask "qbittorrent"
cask "raycast"
cask "rectangle"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"

mas "Xcode", id: 497799835
