brew "docker"
brew "fastfetch"
brew "gh"
brew "git"
brew "java"
brew "mas"
brew "node"
brew "postgresql@15", restart_service: :changed
brew "pyenv"
brew "rbenv"
brew "yarn"

cask "localsend"
cask "docker-desktop"
cask "brave-browser"
cask "github"
cask "localxpose"
cask "mac-mouse-fix"
cask "middleclick"
cask "notion"
cask "postman"
cask "proton-pass"
cask "qbittorrent"
cask "raycast"
cask "rectangle"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "coconutbattery"
cask "font-meslo-for-powerlevel10k"

mas "Xcode", id: 497799835